### ISSUE TITLE
Class list issues when class list has been updated after sorting (P1)

### ISSUE THREAD

**Issue by 3052** [jottocraft/dtps#9] opened 2019-01-25 02:38 UTC
**Describe the bug**
Sidebar incorrectly displays classes. The similarly-named 2nd semester classes all show as the same class.

**Repo steps**
log in to power +

**DEV EDIT: Repo steps**
Login to Power+
Sort classes in the class list
When class list updates (i.e. new semester), various issues show up in the class list

**Expected behavior:**
classes are repeated for 2nd semester variations, but not repeated across all 2nd semester classes

**Actual behavior:**
classes are repeated across all 2nd semester classes
![image](https://user-images.githubusercontent.com/31232125/51721562-3b1b1000-2007-11e9-834d-e9a3891a334d.png)

**Desktop (please complete the following information):**
 - OS with version: [e.g. Windows 10, macOS Mojave]
win 10 pro x64
firefox

**Comment by jottocraft** [comment] 2019-01-25 03:02
This issue seems to have been resolved by clearing Power+ data (clearing Power+ data using the button in the settings menu is the first thing you should do if anything like this happens). It looks like this was caused by some sort of issue with the sorting system in Power+. I'll look out for this in the future and will develop a fix if the issue becomes more widespread.

**Comment by jottocraft** [comment] 2019-01-25 18:45
I'm able to reproduce this issue myself now. This seems to be caused by the class sorting when the class list changes. I'm looking into this issue and will start developing a fix later today. (P1). A fix should be pushed to stable in the coming days ASAP.

**Comment by jottocraft** [comment] 2019-01-25 19:11
https://github.com/jottocraft/dtps/commit/895fd9488d6771de84fa68eb8d651d804d766604 brings a partial fix to the issue in the dev release channel (preventing duplicate classes when a class is removed from the class list). A fix for the class subject mixup is a bit more complex, so it won't be fixed until later today when I have access to my main computer.

**Comment by jottocraft** [comment] 2019-01-25 19:14
issue should be fixed now https://github.com/jottocraft/dtps/commit/4eff21405f60143b89d7007a9bd63476a08971e3. Pushing to stable in ~10 minutes or so

**Closed by jottocraft** 2019-01-25 19:14 UTC
Labels: CR, browser, bug, debugging, help wanted
